services:
  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:8
    command:
      - redis-server
      - --maxmemory
      - ${REDIS_MAXMEMORY}
      - --maxmemory-policy
      - allkeys-lfu
      - --requirepass
      - ${REDIS_PASSWORD}

    ports:
      - 6389:6379

  app:
    image: tds5
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - ${PORT}:${PORT}
