name: tds5
services:
  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 8432:5432

  redis:
    image: redis:8
    command:
      - redis-server
      - --maxmemory
      - ${REDIS_MAXMEMORY}
      - --maxmemory-policy
      - allkeys-lfu
      - --requirepass
      - ${REDIS_PASSWORD}

    ports:
      - 6389:6379

  app:
    build: .
    image: tds5
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${PORT}:${PORT}
