name: Check

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: apps/backend/yarn.lock

      - name: Install dependencies
        shell: bash
        working-directory: apps/backend
        run: yarn install

      - name: Run script
        working-directory: apps/backend
        run: yarn run ${{ inputs.script }}
