name: Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/check.yml
    with:
      script: cicd:lint

  prisma-format-check:
    name: Prisma format check
    uses: ./.github/workflows/check.yml
    with:
      script: cicd:prisma:format-check

  jscpd:
    name: JSCPD
    uses: ./.github/workflows/check.yml
    with:
      script: cicd:jscpd

  knip:
    name: Knip
    uses: ./.github/workflows/check.yml
    with:
      script: cicd:knip

  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/check.yml
    with:
      script: cicd:test

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
#    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        shell: bash
        working-directory: apps/backend
        run: yarn install

      - name: Create .env
        working-directory: apps/backend
        run: echo "${{ secrets.ENV_FILE_E2E }}" > test/.env.e2e

      - name: Run tests
        working-directory: apps/backend
        run: yarn run test:e2e