name: Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run ESLint
        working-directory: apps/backend
        run: yarn run cicd:lint

  prisma-format-check:
    name: Prisma format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run Prisma format check
        working-directory: apps/backend
        run: yarn run cicd:prisma:format-check

  jscpd:
    name: JSCPD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run JSCPD
        working-directory: apps/backend
        run: yarn run cicd:jscpd

  knip:
    name: Knip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run Knip
        working-directory: apps/backend
        run: yarn run cicd:knip

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run tests
        working-directory: apps/backend
        run: yarn run cicd:test

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
#    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Create .env
        working-directory: apps/backend
        run: echo "${{ secrets.ENV_FILE_E2E }}" > test/.env.e2e

      - name: Run tests
        working-directory: apps/backend
        run: yarn run test:e2e